/**
 * Canonical job fixtures mirroring the backend contract (money fields are JSON strings,
 * dates ISO). INV-1042 holds on a +6% price variance; INV-1043 passes clean. These match
 * `backend/app/api/service.py` output shape so component tests exercise the real schema.
 */
import type { JobDetail, ScenarioInfo } from "@/lib/types";

export const SCENARIOS: ScenarioInfo[] = [
  { id: "INV-1042", vendor: "Northwind Supplies", total: "10918.00", currency: "USD" },
  { id: "INV-1043", vendor: "Northwind Supplies", total: "8240.00", currency: "USD" },
];

export const JOB_HOLD: JobDetail = {
  job_id: "job1042abcd",
  invoice_ref: "INV-1042",
  status: "completed",
  decision: "hold",
  outcome: {
    invoice_number: "INV-1042",
    decision: "hold",
    confidence: 0.82,
    blocking_reasons: ["VARIANCE_OUTSIDE_TOLERANCE"],
    summary: "Line 2 unit price is 6% over the PO; holding for approver review.",
    escalation_target: null,
    exception_tickets: [
      {
        ticket_id: "TCK-1",
        exception_type: "VARIANCE_OUTSIDE_TOLERANCE",
        severity: "medium",
        affected_lines: [2],
        suggested_resolution: "Confirm renegotiated price or request a credit.",
        requires_human: true,
        evidence: {},
      },
    ],
  },
  invoice: {
    vendor_name: "Northwind Supplies",
    vendor_id: "V-100",
    invoice_number: "INV-1042",
    invoice_date: "2026-05-10",
    due_date: "2026-06-09",
    currency: "USD",
    subtotal: "10300.00",
    tax_total: "618.00",
    total: "10918.00",
    po_ref: "PO-5001",
    grn_ref: "GRN-7001",
    line_items: [
      {
        line_no: 1,
        sku: "A-1",
        description: "Steel bracket",
        quantity: "100",
        unit_price: "50.00",
        line_total: "5000.00",
        tax_rate: "0.06",
      },
      {
        line_no: 2,
        sku: "B-2",
        description: "Hex bolt pack",
        quantity: "100",
        unit_price: "53.00",
        line_total: "5300.00",
        tax_rate: "0.06",
      },
    ],
    missing_fields: [],
  },
  match: {
    invoice_number: "INV-1042",
    po_number: "PO-5001",
    grn_number: "GRN-7001",
    match_status: "mismatch",
    po_currency: "USD",
    currency_mismatch: false,
    tolerance_version: "2026.04.1",
    lines: [
      {
        invoice_line_no: 1,
        po_line_idx: 0,
        grn_line_idx: 0,
        po_unit_price: "50.00",
        status: "matched",
        quantity_delta: "0",
        price_delta: "0",
        within_tolerance: true,
        received_quantity: "100",
        invoiced_to_date_quantity: "0",
        remaining_billable_quantity: "0",
        over_billed: false,
        resolved_sku: "A-1",
        alias_unresolved: false,
        note: null,
      },
      {
        invoice_line_no: 2,
        po_line_idx: 1,
        grn_line_idx: 1,
        po_unit_price: "50.00",
        status: "price_variance",
        quantity_delta: "0",
        price_delta: "3.00",
        within_tolerance: false,
        received_quantity: "100",
        invoiced_to_date_quantity: "0",
        remaining_billable_quantity: "0",
        over_billed: false,
        resolved_sku: "B-2",
        alias_unresolved: false,
        note: "unit price 6% over PO",
      },
    ],
    citations: [
      {
        document_id: "PO-5001",
        document_title: "Purchase Order PO-5001",
        cited_text: "Line 2 — Hex bolt pack — unit price 50.00 USD",
        page: 1,
        start_char: null,
        end_char: null,
      },
    ],
  },
  variance: {
    invoice_number: "INV-1042",
    overall_severity: "medium",
    financial_impact_total: "300.00",
    thresholds_version: "2026.04.1",
    lines: [
      {
        invoice_line_no: 2,
        financial_impact: "300.00",
        severity: "medium",
        within_tolerance: false,
        rationale: "100 units × 3.00 over PO unit price = 300.00 overbilled.",
      },
    ],
  },
  posting: {
    invoice_number: "INV-1042",
    currency: "USD",
    balanced: true,
    gl_map_version: "ap.gl.v1",
    notes: [],
    lines: [
      { gl_account: "5000", direction: "debit", amount: "10300.00", memo: "Expense" },
      { gl_account: "1360", direction: "debit", amount: "618.00", memo: "Input tax" },
      { gl_account: "2100", direction: "credit", amount: "10918.00", memo: "AP" },
    ],
  },
  review: null,
  handoff_history: [
    {
      from_role: "supervisor",
      to_role: "invoice_extractor",
      reason_code: "delegate",
      detail: "extract invoice INV-1042",
      attempt: 1,
      event_id: "ev-1",
      ts: "2026-05-29T08:00:00Z",
    },
    {
      from_role: "supervisor",
      to_role: "po_grn_matcher",
      reason_code: "delegate",
      detail: "three-way match",
      attempt: 1,
      event_id: "ev-2",
      ts: "2026-05-29T08:00:01Z",
    },
  ],
  events: [
    {
      seq: 1,
      kind: "delegate_result",
      role: "invoice_extractor",
      detail: "extracted 2 lines, total 10918.00",
      ts: "2026-05-29T08:00:00Z",
    },
    {
      seq: 2,
      kind: "delegate_result",
      role: "po_grn_matcher",
      detail: "line 2 price variance vs PO-5001",
      ts: "2026-05-29T08:00:01Z",
    },
    {
      seq: 3,
      kind: "finalize",
      role: "exception_reviewer",
      detail: "hold: VARIANCE_OUTSIDE_TOLERANCE",
      ts: "2026-05-29T08:00:02Z",
    },
  ],
  human_decision: null,
};

export const JOB_PASS: JobDetail = {
  ...JOB_HOLD,
  job_id: "job1043wxyz",
  invoice_ref: "INV-1043",
  decision: "pass",
  outcome: {
    invoice_number: "INV-1043",
    decision: "pass",
    confidence: 0.97,
    blocking_reasons: [],
    summary: "All lines match PO and GRN within tolerance; posting balanced.",
    escalation_target: null,
    exception_tickets: [],
  },
  variance: {
    invoice_number: "INV-1043",
    overall_severity: "none",
    financial_impact_total: "0",
    thresholds_version: "2026.04.1",
    lines: [],
  },
};
